[build]
  functions = "netlify/functions"
  command = "npm install && npm run build"
  publish = "dist" # atau folder React kamu kalau pakai frontend

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200